<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <VssdkCompatibleExtension>true</VssdkCompatibleExtension>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <OutputPath>$(BaseOutputPath)$(Configuration)\</OutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\</IntermediateOutputPath>
    <CreatePkgDefAssemblyToProcess>$(BaseOutputPath)$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).dll</CreatePkgDefAssemblyToProcess>
    <TargetVsixContainerName>RawBufferVisualizer.VisualStudio.Extensibility.vsix</TargetVsixContainerName>
    <AssemblyVersion>2.0.7.0</AssemblyVersion>
    <FileVersion>2.0.7.0</FileVersion>
    <Version>2.0.7</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Extensibility.Build" Version="17.9.2092" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.9.37000" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="17.9.3184" PrivateAssets="all"
                      IncludeAssets="runtime; build; native; contentfiles; analyzers" />
  </ItemGroup>

  <ItemGroup>
    <VSCTCompile Include="RawBufferVisualizerCommands.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawBufferVisualizer.Core\RawBufferVisualizer.Core.csproj" />
    <ProjectReference Include="..\RawBufferVisualizer.OpenGlCanvas\RawBufferVisualizer.OpenGlCanvas.csproj" />
    <ProjectReference Include="..\RawBufferVisualizer.Sdk\RawBufferVisualizer.Sdk.csproj" />
    <ProjectReference Include="..\RawBufferVisualizer.VisualStudio\RawBufferVisualizer.VisualStudio.csproj" />
    <ProjectReference Include="..\RawBufferVisualizer.VisualStudio.Extensibility\RawBufferVisualizer.VisualStudio.Extensibility.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
      <IncludeInVSIX>true</IncludeInVSIX>
      <IncludeOutputGroupsInVSIX>DeploymentAssetsOutputGroup</IncludeOutputGroupsInVSIX>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <VSIXSourceItem Include="$(BaseOutputPath)..\RawBufferVisualizer.VisualStudio.Extensibility\$(Configuration)\net8.0-windows8.0\.vsextension\extension.json"
                    VsixSubPath=".vsextension" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\RawBufferVisualizer.VisualStudio.Extensibility\Resources\Icon.png" Link="Resources\Icon.png">
      <IncludeInVSIX>true</IncludeInVSIX>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\RawBufferVisualizer.VisualStudio.Extensibility\Resources\ReleaseNotes.txt" Link="Resources\ReleaseNotes.txt">
      <IncludeInVSIX>true</IncludeInVSIX>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\LICENSE" Link="LICENSE.txt">
      <IncludeInVSIX>true</IncludeInVSIX>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\THIRD-PARTY-NOTICES.md" Link="THIRD-PARTY-NOTICES.md">
      <IncludeInVSIX>true</IncludeInVSIX>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="GenerateVssdkPkgDef" AfterTargets="Build" DependsOnTargets="CopyPkgDef" />
</Project>
